//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABCtEMP
    {
        public decimal FSessId { get; set; }
        public decimal SessId { get; set; }
        public decimal UserSBillNo { get; set; }
        public string UserBillNo { get; set; }
        public decimal SBillNo { get; set; }
        public string BillNo { get; set; }
        public string RefNo { get; set; }
        public System.DateTime BillDate { get; set; }
        public string CType { get; set; }
        public string SoldBy { get; set; }
        public string BillBy { get; set; }
        public string FType { get; set; }
        public string FCode { get; set; }
        public string PartyName { get; set; }
        public decimal SupplierId { get; set; }
        public string ChDDNo { get; set; }
        public Nullable<System.DateTime> ChDate { get; set; }
        public decimal ChAmt { get; set; }
        public int BankCode { get; set; }
        public string BankName { get; set; }
        public decimal FormNo { get; set; }
        public Nullable<decimal> TotalQty { get; set; }
        public Nullable<decimal> TotalBvValue { get; set; }
        public Nullable<decimal> TotalRPValue { get; set; }
        public Nullable<decimal> TotalNetAmt { get; set; }
        public Nullable<decimal> TotalTaxAmt { get; set; }
        public string RndOff { get; set; }
        public Nullable<decimal> XCXC { get; set; }
        public int TotalSTaxAmount { get; set; }
        public int TotalDiscount { get; set; }
        public Nullable<decimal> TotalKitBvValue { get; set; }
        public int TotalCVValue { get; set; }
        public Nullable<decimal> TotalPVValue { get; set; }
        public int CashDiscPer { get; set; }
        public int CashDiscAmount { get; set; }
        public int CardAmount { get; set; }
        public string PayMode { get; set; }
        public string PayPrefix { get; set; }
        public string Remarks { get; set; }
        public string DispatchStatus { get; set; }
        public string BillTo { get; set; }
        public string BillFor { get; set; }
        public string IsReceive { get; set; }
        public string IsCredit { get; set; }
        public string BillType { get; set; }
        public decimal UserId { get; set; }
        public string UserName { get; set; }
        public string Version { get; set; }
        public string PaymentDtl { get; set; }
        public string IDType { get; set; }
        public string BranchName { get; set; }
        public string UID { get; set; }
        public string ProductId { get; set; }
        public string ProductName { get; set; }
        public string BatchNo { get; set; }
        public string Barcode { get; set; }
        public decimal DispatchQty { get; set; }
        public decimal MRP { get; set; }
        public decimal DP { get; set; }
        public decimal Rate { get; set; }
        public decimal BV { get; set; }
        public decimal BVValue { get; set; }
        public decimal CV { get; set; }
        public Nullable<decimal> CVVDF { get; set; }
        public decimal PV { get; set; }
        public Nullable<decimal> NMKL { get; set; }
        public decimal RP { get; set; }
        public Nullable<decimal> ASDE { get; set; }
        public string IsKitBV { get; set; }
        public string TaxType { get; set; }
        public decimal RTRY { get; set; }
        public decimal HYT { get; set; }
        public int DiscountPer { get; set; }
        public decimal Discount { get; set; }
        public decimal NetAmount { get; set; }
        public string IMEINo { get; set; }
        public int TRE { get; set; }
        public string ItemType { get; set; }
        public decimal FundPoint { get; set; }
        public Nullable<decimal> XX { get; set; }
        public string OrdStatus { get; set; }
        public decimal OrdQty { get; set; }
        public int ProfitVal { get; set; }
        public int DevFundVal { get; set; }
        public Nullable<decimal> DSDS { get; set; }
        public decimal LocId { get; set; }
        public string LocName { get; set; }
        public string Pincode { get; set; }
        public decimal CourierId { get; set; }
        public string CourierName { get; set; }
        public string OrderNo { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string OrderType { get; set; }
        public string Series { get; set; }
        public string DelvAddress { get; set; }
        public string ProdType { get; set; }
        public Nullable<decimal> TAC { get; set; }
        public Nullable<decimal> SDSD { get; set; }
        public Nullable<decimal> GG { get; set; }
        public Nullable<decimal> FF { get; set; }
        public string VV { get; set; }
        public System.DateTime HH { get; set; }
        public string DocketNo { get; set; }
        public Nullable<decimal> DFD { get; set; }
        public int SpclOfferID { get; set; }
        public string DFDF { get; set; }
    }
}
