//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddToCart
    {
        public int Id { get; set; }
        public string ProdId { get; set; }
        public string ProdName { get; set; }
        public decimal Price { get; set; }
        public string ImagePath { get; set; }
        public decimal BV { get; set; }
        public decimal Qty { get; set; }
        public string IPAddress { get; set; }
        public Nullable<int> userId { get; set; }
        public bool posted { get; set; }
        public string UniqueId { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
