//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeletedPartyOrderDetail
    {
        public decimal DId { get; set; }
        public decimal OrderId { get; set; }
        public string OrderNo { get; set; }
        public decimal SOrderNo { get; set; }
        public Nullable<decimal> PLNo { get; set; }
        public System.DateTime PLDate { get; set; }
        public string OrderBy { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public decimal Qty { get; set; }
        public decimal DispatchQty { get; set; }
        public decimal RemQty { get; set; }
        public decimal Weight { get; set; }
        public string Carton { get; set; }
        public string MonoCarton { get; set; }
        public decimal MRP { get; set; }
        public decimal DP { get; set; }
        public decimal Rate { get; set; }
        public decimal Tax { get; set; }
        public string TaxType { get; set; }
        public decimal Amount { get; set; }
        public decimal TaxAmount { get; set; }
        public decimal NetWeight { get; set; }
        public decimal DispatchAmt { get; set; }
        public decimal DispWeight { get; set; }
        public string ProdStatus { get; set; }
        public string PLGen { get; set; }
        public string OrdType { get; set; }
        public string Status { get; set; }
        public string CardStatus { get; set; }
        public string ActiveStatus { get; set; }
        public string Version { get; set; }
        public decimal UserId { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public decimal PLUserId { get; set; }
        public string PLUser { get; set; }
        public Nullable<System.DateTime> PLRecTimeStamp { get; set; }
        public string Transporter { get; set; }
        public string LRNo { get; set; }
        public Nullable<System.DateTime> LRDate { get; set; }
        public string Fld1 { get; set; }
        public string Fld2 { get; set; }
        public string Fld3 { get; set; }
        public string BatchNo { get; set; }
        public string Barcode { get; set; }
        public decimal PLQty { get; set; }
        public decimal PLDispQty { get; set; }
        public decimal PLRemQty { get; set; }
        public string PLStatus { get; set; }
        public string OrderTo { get; set; }
        public decimal MID { get; set; }
        public decimal DiscPer { get; set; }
        public decimal FSessId { get; set; }
        public decimal Discount { get; set; }
        public string IsKit { get; set; }
        public string ProdType { get; set; }
        public decimal BV { get; set; }
        public decimal BVValue { get; set; }
        public decimal RP { get; set; }
        public decimal RPValue { get; set; }
        public int OfferUId { get; set; }
        public decimal VAT { get; set; }
        public decimal DUserId { get; set; }
        public System.DateTime DRecTimeStamp { get; set; }
    }
}
