//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeletedProductDispatchDetail
    {
        public decimal AId { get; set; }
        public decimal BillId { get; set; }
        public string BillNo { get; set; }
        public decimal SBillNo { get; set; }
        public System.DateTime BillDate { get; set; }
        public decimal UserSBillNo { get; set; }
        public string UserBillNo { get; set; }
        public decimal SupplierId { get; set; }
        public string SoldBy { get; set; }
        public string Ftype { get; set; }
        public string RefNo { get; set; }
        public string FCode { get; set; }
        public decimal FormNo { get; set; }
        public string ProductId { get; set; }
        public string ProductName { get; set; }
        public string BatchNo { get; set; }
        public decimal Qty { get; set; }
        public decimal DispatchQty { get; set; }
        public decimal RemainingQty { get; set; }
        public decimal Rate { get; set; }
        public decimal BV { get; set; }
        public decimal BVValue { get; set; }
        public decimal PV { get; set; }
        public decimal PVValue { get; set; }
        public decimal RP { get; set; }
        public decimal RPValue { get; set; }
        public string IsKitBv { get; set; }
        public string TaxType { get; set; }
        public decimal Tax { get; set; }
        public decimal TaxAmount { get; set; }
        public decimal Discount { get; set; }
        public decimal NetAmount { get; set; }
        public string Series { get; set; }
        public string Remarks { get; set; }
        public string BillFor { get; set; }
        public string Imported { get; set; }
        public string IMEINo { get; set; }
        public string BNo { get; set; }
        public System.DateTime DispatchDate { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string ItemType { get; set; }
        public string DispatchStatus { get; set; }
        public string EntryType { get; set; }
        public decimal DP { get; set; }
        public decimal SessId { get; set; }
        public decimal FSessID { get; set; }
        public decimal MSessID { get; set; }
        public string OrderNo { get; set; }
        public string BillType { get; set; }
        public decimal DP1 { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string PartyName { get; set; }
        public decimal MRP { get; set; }
        public string IDType { get; set; }
        public string OrderType { get; set; }
        public string PayMode { get; set; }
        public string ChDDNo { get; set; }
        public Nullable<System.DateTime> ChDate { get; set; }
        public decimal ChAmt { get; set; }
        public string BankName { get; set; }
        public string BranchName { get; set; }
        public string Version { get; set; }
        public decimal UserId { get; set; }
        public string UserName { get; set; }
        public string DispStatus { get; set; }
        public decimal LocId { get; set; }
        public string LocName { get; set; }
        public string Pincode { get; set; }
        public decimal CourierId { get; set; }
        public string CourierName { get; set; }
        public decimal DocWeight { get; set; }
        public string DocketNo { get; set; }
        public Nullable<System.DateTime> DOD { get; set; }
        public string DelvAddress { get; set; }
        public Nullable<System.DateTime> DocketDate { get; set; }
        public string DelvStatus { get; set; }
        public decimal DelvUserId { get; set; }
        public Nullable<System.DateTime> DelvRecTimeStamp { get; set; }
        public decimal PickQty { get; set; }
        public string PLNo { get; set; }
        public Nullable<System.DateTime> PLDate { get; set; }
        public string PLGen { get; set; }
        public decimal DiscountPer { get; set; }
        public string IsKit { get; set; }
        public string ProdType { get; set; }
        public int SpclOfferId { get; set; }
        public int OfferUId { get; set; }
        public decimal DUserId { get; set; }
        public string DReason { get; set; }
        public Nullable<System.DateTime> DRecTimeStamp { get; set; }
    }
}
