//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeletedStockJv
    {
        public decimal OId { get; set; }
        public decimal FSessId { get; set; }
        public decimal JNo { get; set; }
        public string JvNo { get; set; }
        public System.DateTime StockDate { get; set; }
        public string SoldBy { get; set; }
        public string FCode { get; set; }
        public string PartyName { get; set; }
        public string RefNo { get; set; }
        public string ProdId { get; set; }
        public string ProductName { get; set; }
        public string BatchNo { get; set; }
        public string Barcode { get; set; }
        public decimal Qty { get; set; }
        public string JType { get; set; }
        public string Remarks { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public decimal UserId { get; set; }
        public string UserName { get; set; }
        public string Version { get; set; }
        public string ActiveStatus { get; set; }
        public string ProdType { get; set; }
        public string DReason { get; set; }
        public int DUserId { get; set; }
        public System.DateTime DRecTimeStamp { get; set; }
    }
}
