//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeletedPartyOrderMain
    {
        public decimal DId { get; set; }
        public decimal OrderId { get; set; }
        public decimal GroupId { get; set; }
        public decimal PGroupId { get; set; }
        public decimal SOrderNo { get; set; }
        public string OrderNo { get; set; }
        public Nullable<decimal> PLNo { get; set; }
        public System.DateTime PLDate { get; set; }
        public string BillNo { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public string OrderBy { get; set; }
        public string PartyName { get; set; }
        public string OrderTo { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string RefNo { get; set; }
        public string Paymode { get; set; }
        public Nullable<decimal> chNo { get; set; }
        public Nullable<System.DateTime> ChDate { get; set; }
        public Nullable<decimal> ChAmt { get; set; }
        public string BankName { get; set; }
        public decimal TotalWeight { get; set; }
        public decimal TotalOrdQty { get; set; }
        public decimal TotalDispQty { get; set; }
        public decimal TotalRemQty { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal TotalTaxAmt { get; set; }
        public decimal RndOff { get; set; }
        public decimal NetPayable { get; set; }
        public System.DateTime LastPLDate { get; set; }
        public string Remarks { get; set; }
        public string OType { get; set; }
        public decimal PLUserId { get; set; }
        public Nullable<System.DateTime> PLRecTimeStamp { get; set; }
        public string PLUser { get; set; }
        public string IsModify { get; set; }
        public string PLStatus { get; set; }
        public decimal MID { get; set; }
        public string Status { get; set; }
        public string ActiveStatus { get; set; }
        public string Version { get; set; }
        public decimal UserId { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public decimal FSessId { get; set; }
        public string UserName { get; set; }
        public string IsConfirm { get; set; }
        public Nullable<System.DateTime> ConfDate { get; set; }
        public decimal ConfUserID { get; set; }
        public decimal TotalDiscount { get; set; }
        public decimal BankCode { get; set; }
        public decimal TotalBV { get; set; }
        public decimal TotalRP { get; set; }
        public string UID { get; set; }
        public decimal OrderAmount { get; set; }
        public decimal DUserId { get; set; }
        public string DReason { get; set; }
        public System.DateTime DRecTimeStamp { get; set; }
        public string DStatus { get; set; }
    }
}
