//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeletedChallanDetail
    {
        public decimal DId { get; set; }
        public decimal AId { get; set; }
        public decimal FSessId { get; set; }
        public decimal SCNo { get; set; }
        public string ChallanNo { get; set; }
        public System.DateTime ChallanDate { get; set; }
        public string FType { get; set; }
        public string ChallanBy { get; set; }
        public string ChallanTo { get; set; }
        public string ProdId { get; set; }
        public string ProductName { get; set; }
        public string BatchNo { get; set; }
        public decimal MRP { get; set; }
        public decimal Rate { get; set; }
        public decimal Qty { get; set; }
        public decimal Amount { get; set; }
        public decimal Tax { get; set; }
        public decimal TaxAmount { get; set; }
        public string Status { get; set; }
        public decimal UserId { get; set; }
        public string Version { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string IsKit { get; set; }
        public string ProdType { get; set; }
        public decimal DUserId { get; set; }
        public System.DateTime DRecTimeStamp { get; set; }
    }
}
