//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EligibleforProduct250220
    {
        public decimal AID { get; set; }
        public decimal Formno { get; set; }
        public decimal LeftFormno { get; set; }
        public decimal RightFormno { get; set; }
        public System.DateTime ActivationDate { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string ElligForProduct { get; set; }
        public Nullable<System.DateTime> ElligDate { get; set; }
        public string ProductGiven { get; set; }
        public decimal ProdID { get; set; }
        public Nullable<System.DateTime> ProductGivenDate { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> userid { get; set; }
        public string UserName { get; set; }
    }
}
