//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    
    public partial class FranchiseOfferDetail_Result1
    {
        public string OfferName { get; set; }
        public string IdNo { get; set; }
        public string MemFirstName { get; set; }
        public string Mobl { get; set; }
        public Nullable<decimal> PrevTotalAmount { get; set; }
        public Nullable<decimal> PrevTotalAmt2 { get; set; }
        public Nullable<decimal> PrevAmount3 { get; set; }
    }
}
