//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_M_ThemeMaster
    {
        public int AID { get; set; }
        public int BgColorR { get; set; }
        public int BgColorG { get; set; }
        public int BgColorB { get; set; }
        public int HdColorR { get; set; }
        public int HdColorG { get; set; }
        public int HdColorB { get; set; }
        public string ActiveStatus { get; set; }
        public string Remarks { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
    }
}
