//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_M_SearchTypeMaster
    {
        public decimal SearchId { get; set; }
        public string SearchType { get; set; }
        public string ActiveStatus { get; set; }
        public string ColumnName { get; set; }
        public string ShowOn { get; set; }
        public string MethodId { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string ShowAsHdr { get; set; }
        public string ClmType { get; set; }
    }
}
