//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_M_ConfigMaster
    {
        public decimal AId { get; set; }
        public string PIPrefix { get; set; }
        public string ChallanPrefix { get; set; }
        public string BillPrefix { get; set; }
        public string POrderPrefix { get; set; }
        public string SOrderPrefix { get; set; }
        public string PReturnPrefix { get; set; }
        public string SReturnPrefix { get; set; }
        public decimal POrderStartFrm { get; set; }
        public decimal SOrderStartFrm { get; set; }
        public decimal PReturnStartFrm { get; set; }
        public decimal SReturnStartFrm { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public decimal MinOrderAmt { get; set; }
        public decimal CrLimitTimes { get; set; }
        public decimal CrLimitPer { get; set; }
    }
}
