//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_M_UserMaster
    {
        public decimal UId { get; set; }
        public decimal UserId { get; set; }
        public string BranchCode { get; set; }
        public string FCode { get; set; }
        public string UserName { get; set; }
        public string Passw { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public string LastIP { get; set; }
        public System.DateTime LastLoginTime { get; set; }
        public string LastLogOutTime { get; set; }
        public string Version { get; set; }
        public string LoginStatus { get; set; }
        public decimal GroupId { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public decimal LUserId { get; set; }
        public string LastModified { get; set; }
        public string IsAdmin { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
    }
}
