//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InventoryEntities : DbContext
    {
        public InventoryEntities()
            : base("name=InventoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Inv_M_UserMaster> Inv_M_UserMaster { get; set; }
        public virtual DbSet<M_BankMaster> M_BankMaster { get; set; }
        public virtual DbSet<M_BarCodeMaster> M_BarCodeMaster { get; set; }
        public virtual DbSet<M_CatMaster> M_CatMaster { get; set; }
        public virtual DbSet<M_CompanyMaster> M_CompanyMaster { get; set; }
        public virtual DbSet<M_FiscalMaster> M_FiscalMaster { get; set; }
        public virtual DbSet<M_GroupMaster> M_GroupMaster { get; set; }
        public virtual DbSet<M_LedgerMaster> M_LedgerMaster { get; set; }
        public virtual DbSet<M_PayModeMaster> M_PayModeMaster { get; set; }
        public virtual DbSet<M_ProductMaster> M_ProductMaster { get; set; }
        public virtual DbSet<M_SubCatMaster> M_SubCatMaster { get; set; }
        public virtual DbSet<M_TaxMaster> M_TaxMaster { get; set; }
        public virtual DbSet<TrnBillData> TrnBillDatas { get; set; }
        public virtual DbSet<TrnBillDetail> TrnBillDetails { get; set; }
        public virtual DbSet<TrnBillMain> TrnBillMains { get; set; }
        public virtual DbSet<TrnStockJv> TrnStockJvs { get; set; }
        public virtual DbSet<Im_CurrentStock> Im_CurrentStock { get; set; }
        public virtual DbSet<M_NewHOVersionInfo> M_NewHOVersionInfo { get; set; }
        public virtual DbSet<M_SessnMaster> M_SessnMaster { get; set; }
        public virtual DbSet<TrnPayModeDetail> TrnPayModeDetails { get; set; }
        public virtual DbSet<TrnPayModeMaster> TrnPayModeMasters { get; set; }
        public virtual DbSet<V_BillWiseSaleSummary> V_BillWiseSaleSummary { get; set; }
        public virtual DbSet<V_CurrentStockDetailNotForStockist> V_CurrentStockDetailNotForStockist { get; set; }
        public virtual DbSet<M_ConfigMaster> M_ConfigMaster { get; set; }
    }
}
