//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KitOffer
    {
        public decimal AID { get; set; }
        public decimal KitId { get; set; }
        public decimal OfferKid { get; set; }
        public string ProdID { get; set; }
        public string ProdName { get; set; }
        public decimal Rate { get; set; }
        public decimal Qty { get; set; }
        public string OfferDesc { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
    }
}
