//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_BatchMaster
    {
        public decimal BId { get; set; }
        public string BatchBy { get; set; }
        public decimal BatchCode { get; set; }
        public string Pfx { get; set; }
        public string BatchNo { get; set; }
        public string SupplierCode { get; set; }
        public string ProdId { get; set; }
        public decimal Mrp { get; set; }
        public decimal Costing { get; set; }
        public decimal Tax { get; set; }
        public decimal Dp { get; set; }
        public decimal Bv { get; set; }
        public string IsExpired { get; set; }
        public System.DateTime MfgDate { get; set; }
        public System.DateTime ExpDate { get; set; }
        public string ActiveStatus { get; set; }
        public string Remarks { get; set; }
        public string Company { get; set; }
        public string PurchaseFrom { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string Imported { get; set; }
        public decimal DP1 { get; set; }
        public decimal Val1 { get; set; }
        public decimal Val2 { get; set; }
    }
}
