//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_BarCodeMaster
    {
        public decimal AId { get; set; }
        public decimal BId { get; set; }
        public string GenerateBy { get; set; }
        public System.DateTime GenerateDate { get; set; }
        public string SupplierCode { get; set; }
        public string ProdId { get; set; }
        public string BatchNo { get; set; }
        public string BType { get; set; }
        public string BarCodeType { get; set; }
        public decimal BCode { get; set; }
        public string BarCode { get; set; }
        public decimal PRate { get; set; }
        public decimal MRP { get; set; }
        public decimal DP { get; set; }
        public string IsExpired { get; set; }
        public System.DateTime MfgDate { get; set; }
        public System.DateTime ExpDate { get; set; }
        public string Remarks { get; set; }
        public string ActiveStatus { get; set; }
        public string Company { get; set; }
        public string Imported { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public decimal UserId { get; set; }
        public string LastModified { get; set; }
        public decimal DP1 { get; set; }
        public decimal Val1 { get; set; }
        public decimal Val2 { get; set; }
    }
}
