//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_BloodGroupMaster
    {
        public decimal AId { get; set; }
        public decimal BloodId { get; set; }
        public string BloodGroup { get; set; }
        public string ActiveStatus { get; set; }
        public string Remarks { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public decimal UserId { get; set; }
        public string LastModifiedBy { get; set; }
    }
}
