//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_BlockProductMaster
    {
        public int AId { get; set; }
        public int SNo { get; set; }
        public string PartyCode { get; set; }
        public string ProdId { get; set; }
        public string Remarks { get; set; }
        public int UserId { get; set; }
        public System.DateTime RTS { get; set; }
        public string EntryBy { get; set; }
        public string UserName { get; set; }
        public string BlockedFor { get; set; }
    }
}
