//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_CardIssue
    {
        public decimal CardNo { get; set; }
        public string CardType { get; set; }
        public string CodeNo { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime RecTmStamp { get; set; }
        public string Remark { get; set; }
        public string LastIP { get; set; }
        public System.DateTime LastLoginTime { get; set; }
        public string LastLogOutTime { get; set; }
        public string Version { get; set; }
        public string LoginStatus { get; set; }
    }
}
