//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_CatMaster
    {
        public decimal CatId { get; set; }
        public string CatName { get; set; }
        public string Prefix { get; set; }
        public string CatDescription { get; set; }
        public string Remarks { get; set; }
        public string ActiveStatus { get; set; }
        public string Company { get; set; }
        public decimal UserId { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string LastModified { get; set; }
        public string OnWebSite { get; set; }
        public string IsForPC { get; set; }
        public string DelCharge { get; set; }
        public decimal WebSequence { get; set; }
    }
}
