//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_CompanyMaster
    {
        public decimal CId { get; set; }
        public decimal CompId { get; set; }
        public string CompName { get; set; }
        public string CompAdd { get; set; }
        public decimal CompState { get; set; }
        public string CompTinNo { get; set; }
        public string CompSTaxNo { get; set; }
        public string CompPrefix { get; set; }
        public string ContactNo { get; set; }
        public string MobileNo { get; set; }
        public string WebSite { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string LastModified { get; set; }
        public string UserCode { get; set; }
        public decimal UserId { get; set; }
        public string smsSenderId { get; set; }
        public string smsUserNm { get; set; }
        public string smPass { get; set; }
        public string CompMail { get; set; }
        public string CompTitle { get; set; }
        public string CompCSTNo { get; set; }
        public string CompPANNo { get; set; }
        public string MailHost { get; set; }
        public string MailPass { get; set; }
        public string CompRegOffAdd { get; set; }
        public string CompTerm { get; set; }
        public string CompanyIDNo { get; set; }
        public string MsgOnInvoice { get; set; }
        public string WebPortal { get; set; }
        public string IsSendSMS { get; set; }
        public string FTPUserNm { get; set; }
        public string FTPPassw { get; set; }
        public string CompCity { get; set; }
    }
}
