//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_ConfigMaster
    {
        public string IsGetExtreme { get; set; }
        public string IsTopup { get; set; }
        public string IsSendSMS { get; set; }
        public string IsFreeJoin { get; set; }
        public string IsStartJoin { get; set; }
        public System.DateTime JoinStartFrm { get; set; }
        public string IDNoPrefix { get; set; }
        public string IsRandomID { get; set; }
        public string IsSubPlan { get; set; }
        public string DigRandom { get; set; }
        public string IsUploadPic { get; set; }
        public string BillPrefix { get; set; }
        public string IsRefferal { get; set; }
        public string JoinStatus { get; set; }
        public string LogoutPg { get; set; }
        public string GenerateJoiningBill { get; set; }
        public string IsSubCat { get; set; }
        public string BatchPrefix { get; set; }
        public string SendMailOnBill { get; set; }
        public string SendSMSOnBill { get; set; }
        public string SoapAndToothPasteProducts { get; set; }
    }
}
