//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_CustomerMaster
    {
        public decimal AId { get; set; }
        public decimal CustId { get; set; }
        public string CustCode { get; set; }
        public string CustName { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime RegDate { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string RegBy { get; set; }
        public string RegBillNo { get; set; }
        public string NewCustID { get; set; }
        public string SponserID { get; set; }
        public string SponserName { get; set; }
        public string CustFor { get; set; }
        public string ContactNo { get; set; }
        public decimal UserId { get; set; }
        public string CustAddress { get; set; }
        public string CustTIN { get; set; }
    }
}
