//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_DispatchMaster
    {
        public decimal AID { get; set; }
        public decimal DispId { get; set; }
        public string IDNo { get; set; }
        public string MemName { get; set; }
        public decimal KitId { get; set; }
        public string KitName { get; set; }
        public string DispatchType { get; set; }
        public Nullable<System.DateTime> DispDate { get; set; }
        public string CourierName { get; set; }
        public string DocketNo { get; set; }
        public string Remarks { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public decimal UserId { get; set; }
    }
}
