//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_ExtraDiscount
    {
        public decimal SNo { get; set; }
        public decimal GroupId { get; set; }
        public string ProdId { get; set; }
        public decimal DPer { get; set; }
        public decimal ExtraDiscount { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
    }
}
