//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_FlashMaster
    {
        public decimal ID { get; set; }
        public decimal ImgID { get; set; }
        public string ImgText { get; set; }
        public string ImgPath { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string Del_Status { get; set; }
        public string DisplayFor { get; set; }
    }
}
