//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_FormGeneration
    {
        public decimal TransNo { get; set; }
        public System.DateTime StockDate { get; set; }
        public string ProdId { get; set; }
        public decimal FormNo { get; set; }
        public decimal UnitId { get; set; }
        public decimal JId { get; set; }
        public string ChallanNo { get; set; }
        public string GeneratedBy { get; set; }
        public string LastModified { get; set; }
        public string Fcode { get; set; }
        public string SoldBy { get; set; }
        public string SoldTo { get; set; }
        public decimal BvValue { get; set; }
        public string ActiveStatus { get; set; }
        public string Remarks { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string Imported { get; set; }
        public string UpLdStat { get; set; }
        public string ScratchNo { get; set; }
        public string PinType { get; set; }
        public decimal UserId { get; set; }
        public string IsIssued { get; set; }
        public string IsTrans { get; set; }
        public string IsTopUp { get; set; }
        public decimal UsedBy { get; set; }
        public Nullable<System.DateTime> UsedDate { get; set; }
    }
}
