//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_GroupMaster
    {
        public decimal GroupId { get; set; }
        public string GroupName { get; set; }
        public string Prefix { get; set; }
        public string ActiveStatus { get; set; }
        public decimal PgroupId { get; set; }
        public decimal CommissionToParent { get; set; }
        public string OnWebsite { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public decimal PIStartFrm { get; set; }
        public decimal ChallanStartFrm { get; set; }
        public decimal BillStartFrm { get; set; }
        public string MngStkKitWs { get; set; }
        public string InvLogin { get; set; }
        public string Remarks { get; set; }
        public string AllowSTN { get; set; }
        public string SetCrLimit { get; set; }
    }
}
