//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_InsuranceCompMaster
    {
        public decimal AId { get; set; }
        public decimal IncId { get; set; }
        public decimal CompId { get; set; }
        public string CompName { get; set; }
        public string ActiveStatus { get; set; }
        public string Remarks { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public decimal IncPer { get; set; }
        public decimal BVPer { get; set; }
    }
}
