//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_KitProductMaster
    {
        public decimal AId { get; set; }
        public decimal KitId { get; set; }
        public decimal ProdId { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public decimal Rate { get; set; }
        public decimal PCP { get; set; }
        public decimal GrossDP { get; set; }
        public decimal DP { get; set; }
        public decimal Discount { get; set; }
        public decimal CVP { get; set; }
        public decimal QVP { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string ActiveStatus { get; set; }
        public string ProductDesc { get; set; }
        public decimal Tax { get; set; }
        public decimal Qty { get; set; }
        public decimal TaxAmount { get; set; }
        public decimal RatewithoutTax { get; set; }
        public decimal TotalTaxAmt { get; set; }
        public decimal Amount { get; set; }
        public decimal NetPayable { get; set; }
        public string TaxType { get; set; }
        public byte[] ProdImage { get; set; }
        public decimal PV { get; set; }
        public decimal BV { get; set; }
        public string ImagePath { get; set; }
        public decimal CID { get; set; }
        public decimal SCID { get; set; }
        public decimal Offer { get; set; }
        public string IsShow { get; set; }
        public string Del_Status { get; set; }
        public string OrderDesc { get; set; }
    }
}
