//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_KitUnitMaster
    {
        public decimal Uid { get; set; }
        public decimal JId { get; set; }
        public decimal UnitId { get; set; }
        public decimal Unit { get; set; }
        public string KitName { get; set; }
        public decimal UnitAmount { get; set; }
        public decimal RegAmt { get; set; }
        public string IsBooking { get; set; }
        public decimal MaxCV { get; set; }
        public decimal GoldCV { get; set; }
        public string ActiveStatus { get; set; }
        public string IsCompulsoryProduct { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string LastModified { get; set; }
        public string IsPrathvBkng { get; set; }
    }
}
