//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_LogMaster
    {
        public decimal AId { get; set; }
        public decimal UserId { get; set; }
        public string UserName { get; set; }
        public string PartyCode { get; set; }
        public string PartyName { get; set; }
        public string Log { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string UID { get; set; }
    }
}
