//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_MaxDiscount
    {
        public string ProdId { get; set; }
        public decimal MaxDiscount { get; set; }
        public decimal NationId { get; set; }
        public decimal VValue { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public decimal MinAmt { get; set; }
        public string ActiveStatus { get; set; }
        public decimal PackageId { get; set; }
        public string Remarks { get; set; }
        public string IsAllow { get; set; }
    }
}
