//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_MonthSessnMaster
    {
        public decimal SessID { get; set; }
        public Nullable<System.DateTime> FrmDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string OnWebSite { get; set; }
        public decimal Ach { get; set; }
        public decimal Fund { get; set; }
        public decimal Rate { get; set; }
        public decimal MSessId { get; set; }
    }
}
