//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_NewCustomer
    {
        public decimal ID { get; set; }
        public System.DateTime Doj { get; set; }
        public string MemFirstName { get; set; }
        public string MemLastName { get; set; }
        public string Gender { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public decimal CountryID { get; set; }
        public string CountryName { get; set; }
        public decimal StateCode { get; set; }
        public string City { get; set; }
        public decimal PinCode { get; set; }
        public decimal Mobl { get; set; }
        public string EMail { get; set; }
        public decimal FormNo { get; set; }
        public string Passw { get; set; }
        public string UserType { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string IsUpdate { get; set; }
        public string HostIP { get; set; }
    }
}
