//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_ProfessionMaster
    {
        public decimal PID { get; set; }
        public decimal ProfessionID { get; set; }
        public string Profession { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime RectimeStamp { get; set; }
    }
}
