//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_RewardMaster
    {
        public decimal RId { get; set; }
        public decimal RewardId { get; set; }
        public decimal Pair { get; set; }
        public decimal NewPair { get; set; }
        public decimal RLeft { get; set; }
        public decimal RRight { get; set; }
        public string Amount { get; set; }
        public string Reward { get; set; }
        public decimal RDays { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string Rank { get; set; }
        public string ImgPath { get; set; }
    }
}
