//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_SessnMaster
    {
        public decimal SessID { get; set; }
        public Nullable<System.DateTime> FrmDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string OnWebSite { get; set; }
        public string PreExec { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public Nullable<System.DateTime> PreExecRecTimeStamp { get; set; }
        public decimal TopUpRange { get; set; }
        public string ReExec { get; set; }
        public Nullable<System.DateTime> ReExecRecTimeStamp { get; set; }
        public string FinalExec { get; set; }
        public System.DateTime FinalExeRecTimeStamp { get; set; }
        public decimal BlockSessID { get; set; }
    }
}
