//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_SpecialProductMaster
    {
        public decimal AId { get; set; }
        public decimal SpclOfferId { get; set; }
        public string ProdId { get; set; }
        public string IsKit { get; set; }
        public string ProdType { get; set; }
        public string ActiveStatus { get; set; }
        public string Remarks { get; set; }
        public System.DateTime RTS { get; set; }
        public decimal UserId { get; set; }
    }
}
