//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_SpecialOfferMaster
    {
        public decimal AId { get; set; }
        public decimal SpclOfferId { get; set; }
        public string OfferName { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public decimal OfferValue { get; set; }
        public string ValueOn { get; set; }
        public string IsCum { get; set; }
        public string Description { get; set; }
        public string Remarks { get; set; }
        public string ActiveStatus { get; set; }
        public decimal UserId { get; set; }
        public System.DateTime RTS { get; set; }
        public string FreeProdId { get; set; }
        public decimal FreeQty { get; set; }
        public string FreeBatchNo { get; set; }
        public decimal FreeRate { get; set; }
        public string OfferState { get; set; }
    }
}
