//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_TaxCatMaster
    {
        public decimal AId { get; set; }
        public decimal TxId { get; set; }
        public string TaxType { get; set; }
        public string TaxPrefix { get; set; }
        public decimal TaxValue { get; set; }
        public string Description { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public decimal UserId { get; set; }
        public string LastModified { get; set; }
    }
}
