//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_ThemeMaster
    {
        public decimal TId { get; set; }
        public string ThemeName { get; set; }
        public string ShowAs { get; set; }
        public string ActiveStatus { get; set; }
        public string ActiveTheme { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
    }
}
