//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Wishlist
    {
        public decimal Aid { get; set; }
        public decimal Formno { get; set; }
        public decimal Productid { get; set; }
        public string ProductName { get; set; }
        public decimal Qty { get; set; }
        public System.DateTime RectimeStamp { get; set; }
    }
}
