//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MakeKit
    {
        public decimal AID { get; set; }
        public decimal ID { get; set; }
        public decimal KitID { get; set; }
        public string KitName { get; set; }
        public decimal Qty { get; set; }
        public string ConvType { get; set; }
        public string ActiveStatus { get; set; }
        public decimal UserID { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
    }
}
