//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferAchvdMem
    {
        public decimal AID { get; set; }
        public decimal Formno { get; set; }
        public decimal FrmDate { get; set; }
        public decimal ToDate { get; set; }
        public decimal OfferUID { get; set; }
    }
}
