//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OLDBillDetail
    {
        public decimal AID { get; set; }
        public string BillNo { get; set; }
        public string ProductID { get; set; }
        public string ProductName { get; set; }
        public decimal MRP { get; set; }
        public decimal DP { get; set; }
        public decimal Qty { get; set; }
        public decimal NetAmount { get; set; }
        public decimal MRPValue { get; set; }
        public decimal PValue { get; set; }
        public string TaxType { get; set; }
        public decimal CGST { get; set; }
        public decimal SGST { get; set; }
        public decimal IGST { get; set; }
    }
}
