//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public string ProdId { get; set; }
        public string ProdName { get; set; }
        public decimal Price { get; set; }
        public decimal qty { get; set; }
        public decimal bv { get; set; }
        public int userId { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
