//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendLoginSM
    {
        public decimal AID { get; set; }
        public string MobileNo { get; set; }
        public string Sms { get; set; }
        public string IsExpired { get; set; }
        public string IsSent { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public Nullable<System.DateTime> SentTime { get; set; }
        public string OTP { get; set; }
        public string Email { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
