//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockOrderWishlist
    {
        public string OrderBy { get; set; }
        public string OrderTo { get; set; }
        public string ProductId { get; set; }
        public string ProductName { get; set; }
        public string Qunatity { get; set; }
        public string ActiveStatus { get; set; }
        public int AId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
    }
}
