//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TargetMaster
    {
        public decimal AID { get; set; }
        public decimal TID { get; set; }
        public System.DateTime FrmDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public string OnValue { get; set; }
        public decimal MaxValue { get; set; }
        public decimal CommPer { get; set; }
        public decimal UserID { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
    }
}
