//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TargetDetail
    {
        public decimal AID { get; set; }
        public decimal TID { get; set; }
        public decimal CatID { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
    }
}
