//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAddressDetail
    {
        public int Aid { get; set; }
        public Nullable<int> userid { get; set; }
        public string passw { get; set; }
        public string Firstname { get; set; }
        public string lastname { get; set; }
        public string FormNo { get; set; }
        public string idNo { get; set; }
        public string Address1 { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string StateCode { get; set; }
        public string PinCode { get; set; }
        public string MobileNo { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
