//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUserPoint
    {
        public int UPID { get; set; }
        public Nullable<int> ProdId { get; set; }
        public string FormNo { get; set; }
        public string RandomId { get; set; }
        public string UserName { get; set; }
        public Nullable<decimal> Points { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
