//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempCompBankersMaster
    {
        public decimal TId { get; set; }
        public decimal AId { get; set; }
        public decimal CBCode { get; set; }
        public decimal BankCode { get; set; }
        public string BranchName { get; set; }
        public string AcNo { get; set; }
        public string IFSCCode { get; set; }
        public string Remarks { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public decimal UserId { get; set; }
        public string LastModified { get; set; }
        public decimal MUserId { get; set; }
        public System.DateTime MRecTimeStamp { get; set; }
    }
}
