//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempTaxMaster
    {
        public decimal TId { get; set; }
        public decimal AId { get; set; }
        public string GenerateBy { get; set; }
        public string ProdCode { get; set; }
        public string ProdName { get; set; }
        public decimal StateCode { get; set; }
        public decimal VatTax { get; set; }
        public decimal STax { get; set; }
        public decimal CstTax { get; set; }
        public decimal WithCForm { get; set; }
        public decimal AValue { get; set; }
        public string ActiveStatus { get; set; }
        public string Remarks { get; set; }
        public string Company { get; set; }
        public string Imported { get; set; }
        public decimal UserId { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string LastModified { get; set; }
        public decimal MUserId { get; set; }
        public System.DateTime MRecTimeStamp { get; set; }
    }
}
