//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempOrderAddress
    {
        public int AID { get; set; }
        public decimal OrderNo { get; set; }
        public decimal FormNo { get; set; }
        public string Address1 { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
    }
}
