//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempVoucher
    {
        public decimal VoucherId { get; set; }
        public decimal VoucherNo { get; set; }
        public System.DateTime VoucherDate { get; set; }
        public string DrTo { get; set; }
        public string CrTo { get; set; }
        public decimal Amount { get; set; }
        public string Narration { get; set; }
        public string RefNo { get; set; }
        public decimal AccDocNo { get; set; }
        public string AccDocType { get; set; }
        public System.DateTime AccDocDate { get; set; }
        public string AccRemark { get; set; }
        public string AccTransKey { get; set; }
        public string AccParentKey { get; set; }
        public string AccCompany { get; set; }
        public string Remarks { get; set; }
    }
}
