//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempProductMaster
    {
        public decimal TId { get; set; }
        public decimal AId { get; set; }
        public string GenerateBy { get; set; }
        public decimal BrandCode { get; set; }
        public decimal CatId { get; set; }
        public decimal SubCatId { get; set; }
        public string ProductType { get; set; }
        public string UserProdId { get; set; }
        public decimal ProductCode { get; set; }
        public string ProdId { get; set; }
        public string ProductName { get; set; }
        public string ProductDesc { get; set; }
        public string Prefix { get; set; }
        public string ItemType { get; set; }
        public decimal BuyingTax { get; set; }
        public decimal Weight { get; set; }
        public decimal PurchaseRate { get; set; }
        public decimal MRP { get; set; }
        public decimal DP { get; set; }
        public decimal DP1 { get; set; }
        public decimal OtherStateDP { get; set; }
        public decimal Exp { get; set; }
        public decimal Costing { get; set; }
        public decimal BV { get; set; }
        public decimal CV { get; set; }
        public decimal PV { get; set; }
        public decimal RP { get; set; }
        public decimal FundPoint { get; set; }
        public string IsDiscount { get; set; }
        public decimal Discount { get; set; }
        public decimal DiscInRs { get; set; }
        public decimal VDiscount { get; set; }
        public decimal ProdCommssn { get; set; }
        public decimal GRate { get; set; }
        public decimal GMCharge { get; set; }
        public string GMType { get; set; }
        public string IsCardIssue { get; set; }
        public string Remarks { get; set; }
        public string ActiveStatus { get; set; }
        public string IsImage { get; set; }
        public string ImagePath { get; set; }
        public string OnWebSite { get; set; }
        public string TaxType { get; set; }
        public string Company { get; set; }
        public string PurchaseFrom { get; set; }
        public string PurchaseStore { get; set; }
        public string Imported { get; set; }
        public string IMEINo { get; set; }
        public string BNo { get; set; }
        public string PType { get; set; }
        public decimal BId { get; set; }
        public string BarcodeType { get; set; }
        public decimal BCode { get; set; }
        public string Barcode { get; set; }
        public string IsExpired { get; set; }
        public System.DateTime MfgDate { get; set; }
        public System.DateTime ExpDate { get; set; }
        public decimal OpStockQty { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public decimal UserId { get; set; }
        public string LastModified { get; set; }
        public decimal Val1 { get; set; }
        public decimal Val2 { get; set; }
        public string OrderDesc { get; set; }
        public string SpclOffer { get; set; }
        public string HotSell { get; set; }
        public string IsForPC { get; set; }
        public string IsFlexible { get; set; }
        public decimal Qty { get; set; }
        public string CalcKitRate { get; set; }
        public decimal FlexiQty { get; set; }
        public string MsgText { get; set; }
        public string MsgStatus { get; set; }
        public string ImgPath1 { get; set; }
        public string ImgPath2 { get; set; }
        public string ImgPath3 { get; set; }
        public string ImgPath4 { get; set; }
        public decimal AlterID { get; set; }
        public string HSNCode { get; set; }
        public decimal MUserId { get; set; }
        public System.DateTime MRecTimeStamp { get; set; }
    }
}
