//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempCityStateMaster
    {
        public decimal TId { get; set; }
        public decimal AId { get; set; }
        public decimal StateCode { get; set; }
        public decimal DistrictCode { get; set; }
        public decimal CityCode { get; set; }
        public string CityName { get; set; }
        public string PinCode { get; set; }
        public string ActiveStatus { get; set; }
        public string Remarks { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string LastModified { get; set; }
        public string UserCode { get; set; }
        public decimal UserId { get; set; }
        public string Version { get; set; }
        public decimal MUserId { get; set; }
        public System.DateTime MRecTimeStamp { get; set; }
    }
}
