//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempProductBookingMaster
    {
        public decimal AId { get; set; }
        public string ProdId { get; set; }
        public decimal Rate { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string Remarks { get; set; }
        public decimal SepRate { get; set; }
        public decimal OctRate { get; set; }
        public decimal JanRate { get; set; }
        public decimal OtherRate { get; set; }
    }
}
