//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempNewHOVersionInfo
    {
        public decimal TId { get; set; }
        public decimal AId { get; set; }
        public string LastVersionNo { get; set; }
        public string LastVersionDate { get; set; }
        public string VersionNo { get; set; }
        public string VersionDate { get; set; }
        public string VerDesc { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public System.DateTime URecTimeStamp { get; set; }
    }
}
