//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempLedgerMaster
    {
        public decimal TId { get; set; }
        public decimal AId { get; set; }
        public decimal GroupId { get; set; }
        public decimal PGroupId { get; set; }
        public string UserPartyCode { get; set; }
        public decimal PCode { get; set; }
        public string PartyCode { get; set; }
        public string ParentPartyCode { get; set; }
        public string PartyName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public decimal StateCode { get; set; }
        public decimal CityCode { get; set; }
        public string CityName { get; set; }
        public string Tehsil { get; set; }
        public decimal PinCode { get; set; }
        public string PhoneNo { get; set; }
        public decimal MobileNo { get; set; }
        public string FaxNo { get; set; }
        public string PanNo { get; set; }
        public string TinNo { get; set; }
        public string CstNo { get; set; }
        public string STaxNo { get; set; }
        public string BankAcNo { get; set; }
        public decimal BankCode { get; set; }
        public string BankName { get; set; }
        public string RequestTo { get; set; }
        public string AccountVerify { get; set; }
        public string RecommandBy { get; set; }
        public string ContactPerson { get; set; }
        public string E_MailAdd { get; set; }
        public string ActiveStatus { get; set; }
        public string OnWebSite { get; set; }
        public decimal CreditLimit { get; set; }
        public string Remarks { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string NewFld1 { get; set; }
        public string NewFld2 { get; set; }
        public string NewFld3 { get; set; }
        public string NewFld4 { get; set; }
        public string Company { get; set; }
        public decimal UserId { get; set; }
        public string UserName { get; set; }
        public string LastModified { get; set; }
        public string RecvdCForm { get; set; }
        public decimal MUserId { get; set; }
        public System.DateTime MRecTimeStamp { get; set; }
    }
}
