//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempChildProductRegistration
    {
        public decimal TId { get; set; }
        public decimal TransNo { get; set; }
        public string ParentProdId { get; set; }
        public string ParentBatchNo { get; set; }
        public string SubProdId { get; set; }
        public string SubBatchNo { get; set; }
        public decimal OfferId { get; set; }
        public decimal ProductOfferId { get; set; }
        public decimal ParentProdQty { get; set; }
        public decimal SubProdQty { get; set; }
        public decimal DP { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string IsCardIssue { get; set; }
        public Nullable<System.DateTime> RecTimeStamp { get; set; }
        public string Scheme { get; set; }
        public string TaxApplied { get; set; }
        public string BvApplied { get; set; }
        public string IsDiscount { get; set; }
        public string Remarks { get; set; }
        public string Company { get; set; }
        public string ActiveStatus { get; set; }
        public decimal UID { get; set; }
        public string ParentType { get; set; }
        public decimal MaxParent { get; set; }
        public decimal DP1 { get; set; }
        public string IsFlexible { get; set; }
        public decimal TotalQty { get; set; }
        public decimal TotalSubQty { get; set; }
        public decimal DiscPer { get; set; }
        public string ProdType { get; set; }
        public string IsSallable { get; set; }
        public string TReason { get; set; }
        public int TUserId { get; set; }
        public System.DateTime TRecTimeStamp { get; set; }
    }
}
