//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempNewOfferMaster
    {
        public decimal AId { get; set; }
        public decimal UId { get; set; }
        public decimal ProductOfferId { get; set; }
        public string ParentProdId { get; set; }
        public string ParentBatchNo { get; set; }
        public decimal ParentProdQty { get; set; }
        public decimal OfferId { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string ParentType { get; set; }
        public decimal MaxParent { get; set; }
        public string MngStock { get; set; }
        public string OfferFor { get; set; }
        public string CodeDtl { get; set; }
        public string IsSpclOffer { get; set; }
        public int SpclOfferId { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public decimal UserId { get; set; }
        public System.DateTime MRecTimeStamp { get; set; }
        public int MUserID { get; set; }
    }
}
