//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrnBillData
    {
        public decimal AId { get; set; }
        public decimal FSessId { get; set; }
        public decimal SessId { get; set; }
        public decimal SBillNo { get; set; }
        public string BillNo { get; set; }
        public string RefNo { get; set; }
        public System.DateTime BillDate { get; set; }
        public string CType { get; set; }
        public string SoldBy { get; set; }
        public string BillBy { get; set; }
        public string FType { get; set; }
        public string FCode { get; set; }
        public string PartyName { get; set; }
        public decimal SupplierId { get; set; }
        public decimal ChDDNo { get; set; }
        public Nullable<System.DateTime> ChDate { get; set; }
        public decimal ChAmt { get; set; }
        public decimal BankCode { get; set; }
        public string BankName { get; set; }
        public decimal FormNo { get; set; }
        public decimal TotalTaxAmount { get; set; }
        public decimal TotalSTaxAmount { get; set; }
        public decimal TotalDiscount { get; set; }
        public decimal TotalKitBvValue { get; set; }
        public decimal TotalBvValue { get; set; }
        public decimal TotalCVValue { get; set; }
        public decimal TotalPVValue { get; set; }
        public decimal TotalRPValue { get; set; }
        public decimal CashDiscPer { get; set; }
        public decimal CashDiscAmount { get; set; }
        public decimal NetPayable { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal RndOff { get; set; }
        public decimal CardAmount { get; set; }
        public string PayMode { get; set; }
        public string PayPrefix { get; set; }
        public string BvTransfer { get; set; }
        public string Remarks { get; set; }
        public string DispatchStatus { get; set; }
        public string LR { get; set; }
        public Nullable<System.DateTime> LRDate { get; set; }
        public string TransporterName { get; set; }
        public string DispatchTo { get; set; }
        public string FreightType { get; set; }
        public decimal FreightAmt { get; set; }
        public string Series { get; set; }
        public string Scratch { get; set; }
        public decimal RefId { get; set; }
        public string RefName { get; set; }
        public string JType { get; set; }
        public decimal Unit { get; set; }
        public string BillTo { get; set; }
        public decimal PSessId { get; set; }
        public string BillFor { get; set; }
        public string DcNo { get; set; }
        public string Imported { get; set; }
        public string IsReceive { get; set; }
        public string IsCredit { get; set; }
        public string BillType { get; set; }
        public decimal TotalDiscountAmt { get; set; }
        public decimal VDiscountAmt { get; set; }
        public string ReceiverID { get; set; }
        public string ReceiverName { get; set; }
        public string ReceiverMNo { get; set; }
        public string ReceiverIDProof { get; set; }
        public decimal TotalFPoint { get; set; }
        public decimal TotalQty { get; set; }
        public decimal CommssnAmt { get; set; }
        public decimal CashReward { get; set; }
        public decimal RecvAmount { get; set; }
        public decimal ReturnToCustAmt { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public decimal UserId { get; set; }
        public string UserName { get; set; }
        public string Version { get; set; }
        public string DelvPlace { get; set; }
        public string PaymentDtl { get; set; }
        public string IDType { get; set; }
        public string BranchName { get; set; }
        public decimal LocId { get; set; }
        public string LocName { get; set; }
        public string Pincode { get; set; }
        public decimal CourierId { get; set; }
        public string CourierName { get; set; }
        public string ProductId { get; set; }
        public string ProductName { get; set; }
        public string BatchNo { get; set; }
        public string Barcode { get; set; }
        public decimal Qty { get; set; }
        public decimal MRP { get; set; }
        public decimal DP { get; set; }
        public decimal Rate { get; set; }
        public decimal BV { get; set; }
        public decimal BVValue { get; set; }
        public decimal CV { get; set; }
        public decimal CVValue { get; set; }
        public decimal PV { get; set; }
        public decimal PVValue { get; set; }
        public decimal RP { get; set; }
        public decimal RPValue { get; set; }
        public string IsKitBV { get; set; }
        public string TaxType { get; set; }
        public decimal Tax { get; set; }
        public decimal TaxAmount { get; set; }
        public decimal DiscountPer { get; set; }
        public decimal Discount { get; set; }
        public decimal NetAmount { get; set; }
        public string DSeries { get; set; }
        public string DImported { get; set; }
        public string IMEINo { get; set; }
        public string BNo { get; set; }
        public string ItemType { get; set; }
        public decimal VDiscount { get; set; }
        public decimal VDiscountValue { get; set; }
        public decimal FPoint { get; set; }
        public decimal FPointValue { get; set; }
        public decimal ProdCommssn { get; set; }
        public decimal ProdCommssnAmt { get; set; }
        public string OrdStatus { get; set; }
        public decimal OrdQty { get; set; }
        public decimal RemQty { get; set; }
        public decimal DP1 { get; set; }
        public string DReason { get; set; }
        public decimal DUserId { get; set; }
        public Nullable<System.DateTime> DRecTimeStamp { get; set; }
        public decimal DocWeight { get; set; }
        public string DocketNo { get; set; }
        public Nullable<System.DateTime> DOD { get; set; }
        public string DelvAddress { get; set; }
        public string OrderNo { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> DocketDate { get; set; }
        public string DelvStatus { get; set; }
        public decimal DelvUserId { get; set; }
        public Nullable<System.DateTime> DelvRecTimeStamp { get; set; }
        public string OrderType { get; set; }
        public string UserBillNo { get; set; }
        public decimal UserSBillNo { get; set; }
        public string STNFormNo { get; set; }
        public string StkRecv { get; set; }
        public Nullable<System.DateTime> StkRecvDate { get; set; }
        public decimal StkRecvUserId { get; set; }
        public string InTransit { get; set; }
        public string UID { get; set; }
        public decimal OfferUID { get; set; }
        public string IsKit { get; set; }
        public string ProdType { get; set; }
        public string TotalCorton { get; set; }
        public string TotalMonoCorton { get; set; }
        public int SpclOfferId { get; set; }
        public decimal VAT { get; set; }
        public string BuyerAddress { get; set; }
        public string BuyerTIN { get; set; }
        public decimal CGST { get; set; }
        public decimal CGSTAmt { get; set; }
        public decimal SGST { get; set; }
        public decimal SGSTAmt { get; set; }
        public Nullable<int> FreeQty { get; set; }
    }
}
