//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrnBillDetail
    {
        public decimal BillId { get; set; }
        public decimal FSessId { get; set; }
        public decimal SessId { get; set; }
        public decimal SBillNo { get; set; }
        public string BillNo { get; set; }
        public System.DateTime BillDate { get; set; }
        public decimal SupplierId { get; set; }
        public string SoldBy { get; set; }
        public string FType { get; set; }
        public string RefNo { get; set; }
        public string FCode { get; set; }
        public decimal FormNo { get; set; }
        public string ProductId { get; set; }
        public string ProductName { get; set; }
        public string BatchNo { get; set; }
        public string Barcode { get; set; }
        public decimal Qty { get; set; }
        public decimal MRP { get; set; }
        public decimal DP { get; set; }
        public decimal Rate { get; set; }
        public decimal BV { get; set; }
        public decimal BvValue { get; set; }
        public decimal CV { get; set; }
        public decimal CVValue { get; set; }
        public decimal PV { get; set; }
        public decimal PVValue { get; set; }
        public decimal RP { get; set; }
        public decimal RPValue { get; set; }
        public string IsKitBv { get; set; }
        public decimal DiscountPer { get; set; }
        public decimal Discount { get; set; }
        public decimal ProdCommssn { get; set; }
        public decimal ProdCommssnAmt { get; set; }
        public string TaxType { get; set; }
        public decimal Tax { get; set; }
        public decimal TaxAmount { get; set; }
        public decimal NetAmount { get; set; }
        public string Series { get; set; }
        public string Remarks { get; set; }
        public string BillFor { get; set; }
        public string Imported { get; set; }
        public string IMEINo { get; set; }
        public string BNo { get; set; }
        public string ItemType { get; set; }
        public decimal VDiscount { get; set; }
        public decimal VDiscountValue { get; set; }
        public decimal FPoint { get; set; }
        public decimal FPointValue { get; set; }
        public string ActiveStatus { get; set; }
        public decimal UserId { get; set; }
        public string Version { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string OrdStatus { get; set; }
        public decimal OrdQty { get; set; }
        public decimal RemQty { get; set; }
        public decimal DP1 { get; set; }
        public decimal OfferUID { get; set; }
        public string IsKit { get; set; }
        public string ProdType { get; set; }
        public int SpclOfferId { get; set; }
        public decimal VAT { get; set; }
        public decimal CGST { get; set; }
        public decimal CGSTAmt { get; set; }
        public decimal SGST { get; set; }
        public decimal SGSTAmt { get; set; }
        public string UID { get; set; }
        public Nullable<int> FreeQty { get; set; }
    }
}
