//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrnChallanMain
    {
        public decimal AId { get; set; }
        public decimal FSessId { get; set; }
        public decimal SCNo { get; set; }
        public string ChallanNo { get; set; }
        public System.DateTime ChallanDate { get; set; }
        public string RefNo { get; set; }
        public string FType { get; set; }
        public string ChallanBy { get; set; }
        public string ChallanTo { get; set; }
        public string PartyName { get; set; }
        public decimal TotalQty { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal TaxAmount { get; set; }
        public decimal RndOff { get; set; }
        public decimal NetPayable { get; set; }
        public string Remarks { get; set; }
        public string ChallanFor { get; set; }
        public string Status { get; set; }
        public string ActiveStatus { get; set; }
        public decimal UserId { get; set; }
        public string UserName { get; set; }
        public string Version { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string PartyAdd { get; set; }
        public string ContactNo { get; set; }
    }
}
