//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrnCancelOrder
    {
        public decimal TID { get; set; }
        public decimal ID { get; set; }
        public decimal OrderNo { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string MemFirstName { get; set; }
        public string MemLastName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public decimal CountryID { get; set; }
        public string CountryName { get; set; }
        public decimal StateCode { get; set; }
        public string District { get; set; }
        public string City { get; set; }
        public decimal PinCode { get; set; }
        public decimal Mobl { get; set; }
        public string EMail { get; set; }
        public decimal FormNo { get; set; }
        public string UserType { get; set; }
        public string Passw { get; set; }
        public string PayMode { get; set; }
        public decimal ChDDNo { get; set; }
        public System.DateTime ChDate { get; set; }
        public decimal ChAmt { get; set; }
        public string BankName { get; set; }
        public string BranchName { get; set; }
        public string Remark { get; set; }
        public decimal GroupNo { get; set; }
        public string OrderType { get; set; }
        public decimal OrderAmt { get; set; }
        public decimal OrderItem { get; set; }
        public decimal OrderQty { get; set; }
        public decimal OrderQvp { get; set; }
        public decimal OrderCvp { get; set; }
        public decimal OrderByFormNo { get; set; }
        public string ActiveStatus { get; set; }
        public string HostIp { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string IsTransfer { get; set; }
        public Nullable<System.DateTime> DispatchDate { get; set; }
        public string DispatchStatus { get; set; }
        public decimal DispatchQty { get; set; }
        public decimal RemainQty { get; set; }
        public decimal DispatchAmount { get; set; }
        public decimal Shipping { get; set; }
        public decimal SessID { get; set; }
        public byte[] RcptImage { get; set; }
        public Nullable<decimal> StatusCode { get; set; }
        public string IDType { get; set; }
        public string IDNo { get; set; }
        public string IsConfirm { get; set; }
        public Nullable<System.DateTime> ConfDate { get; set; }
        public decimal ConfUserId { get; set; }
        public string OrderFor { get; set; }
        public string DepositAcNm { get; set; }
        public Nullable<decimal> DepositAcNo { get; set; }
        public string DepositBank { get; set; }
        public string DepositBranch { get; set; }
        public string DepositIfsc { get; set; }
        public decimal MSessID { get; set; }
        public decimal RefFormNo { get; set; }
        public decimal DiscPer { get; set; }
        public decimal Discount { get; set; }
        public decimal OldShipping { get; set; }
        public string ShippingStatus { get; set; }
        public decimal PromoID { get; set; }
        public decimal VoucherAmt { get; set; }
        public string IsVoucher { get; set; }
        public decimal ActQvp { get; set; }
        public decimal EarnPoints { get; set; }
        public string CancelReason { get; set; }
        public string CancelBy { get; set; }
        public string Type { get; set; }
    }
}
