//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrnOrderDeliveryDetail
    {
        public decimal AId { get; set; }
        public decimal SNo { get; set; }
        public string SoldBy { get; set; }
        public string OrderNo { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string BillNo { get; set; }
        public System.DateTime BillDate { get; set; }
        public decimal CourierId { get; set; }
        public string CourierName { get; set; }
        public string DocketNo { get; set; }
        public Nullable<System.DateTime> DocketDate { get; set; }
        public decimal DocWeight { get; set; }
        public Nullable<System.DateTime> DOD { get; set; }
        public string DelvAddress { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public decimal UserId { get; set; }
        public string TotalCorton { get; set; }
        public string TotalMonoCorton { get; set; }
        public string BillType { get; set; }
        public Nullable<System.DateTime> DRecTimeStamp { get; set; }
        public string ReturnRemark { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
    }
}
