//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrnPaymentConfirmation
    {
        public decimal AId { get; set; }
        public decimal SNo { get; set; }
        public string ConfirmBy { get; set; }
        public string OrderNo { get; set; }
        public decimal FormNo { get; set; }
        public decimal OrderAmt { get; set; }
        public string IsConfirm { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public decimal UserID { get; set; }
        public string OrderFor { get; set; }
        public string IDNO { get; set; }
        public string ActiveStatus { get; set; }
        public decimal DUserId { get; set; }
        public string DReason { get; set; }
        public Nullable<System.DateTime> DRecTimeStamp { get; set; }
        public string OrdType { get; set; }
        public int FSessId { get; set; }
    }
}
