//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrnProductMain
    {
        public decimal BillId { get; set; }
        public string BillNo { get; set; }
        public decimal SBillNo { get; set; }
        public System.DateTime BillDate { get; set; }
        public string Ctype { get; set; }
        public string SoldBy { get; set; }
        public string BillBy { get; set; }
        public string Ftype { get; set; }
        public string Fcode { get; set; }
        public string PartyName { get; set; }
        public decimal SupplierId { get; set; }
        public Nullable<decimal> ChDDNo { get; set; }
        public Nullable<System.DateTime> ChDate { get; set; }
        public Nullable<decimal> ChAmt { get; set; }
        public string BankName { get; set; }
        public decimal FormNo { get; set; }
        public decimal TaxAmount { get; set; }
        public decimal STaxAmount { get; set; }
        public decimal Discount { get; set; }
        public decimal KitBvValue { get; set; }
        public decimal BvValue { get; set; }
        public decimal DispatchBVValue { get; set; }
        public decimal RPValue { get; set; }
        public decimal NetPayable { get; set; }
        public decimal Amount { get; set; }
        public decimal RndOff { get; set; }
        public decimal CardAmount { get; set; }
        public string PayMode { get; set; }
        public decimal SessId { get; set; }
        public string BvTransfer { get; set; }
        public string Remarks { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string DispatchStatus { get; set; }
        public string LR { get; set; }
        public System.DateTime LRDate { get; set; }
        public string TransporterName { get; set; }
        public string DispatchTo { get; set; }
        public string FreightType { get; set; }
        public decimal FreightAmt { get; set; }
        public string Series { get; set; }
        public string Scratch { get; set; }
        public decimal RefId { get; set; }
        public string RefName { get; set; }
        public string JType { get; set; }
        public decimal Unit { get; set; }
        public string BillTo { get; set; }
        public decimal PSessId { get; set; }
        public string BillFor { get; set; }
        public string DcNo { get; set; }
        public string Imported { get; set; }
        public string IsReceive { get; set; }
        public string IsCredit { get; set; }
        public string BillType { get; set; }
        public decimal DiscountAmt { get; set; }
        public string BranchName { get; set; }
    }
}
