//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrnPurchaseReqDetail
    {
        public decimal AId { get; set; }
        public decimal SessID { get; set; }
        public decimal FSessID { get; set; }
        public string ReqNo { get; set; }
        public System.DateTime ReqDate { get; set; }
        public string ProdID { get; set; }
        public string ProductName { get; set; }
        public decimal Qty { get; set; }
        public decimal DP { get; set; }
        public decimal MRP { get; set; }
        public decimal PRate { get; set; }
        public decimal Amount { get; set; }
        public decimal DispQty { get; set; }
        public decimal RemQty { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public string ActiveStatus { get; set; }
        public string Version { get; set; }
        public decimal UserId { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
    }
}
