//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrnPurchaseOrderDetail
    {
        public decimal OrderId { get; set; }
        public decimal SessID { get; set; }
        public decimal FSessID { get; set; }
        public decimal SOrderNo { get; set; }
        public string OrderNo { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string RefNo { get; set; }
        public string OrderBy { get; set; }
        public string SuppCode { get; set; }
        public string PartyCode { get; set; }
        public string ProdID { get; set; }
        public string ProductName { get; set; }
        public decimal Qty { get; set; }
        public decimal MRP { get; set; }
        public decimal PRate { get; set; }
        public decimal Amount { get; set; }
        public decimal DispQty { get; set; }
        public decimal RemQty { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public string ActiveStatus { get; set; }
        public string Version { get; set; }
        public decimal UserId { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public decimal DP { get; set; }
        public Nullable<System.DateTime> MfgDate { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
    }
}
