//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrnPurchaseReqMain
    {
        public decimal AId { get; set; }
        public decimal SessID { get; set; }
        public decimal FSessID { get; set; }
        public decimal SReqNo { get; set; }
        public string ReqNo { get; set; }
        public System.DateTime ReqDate { get; set; }
        public string RefNo { get; set; }
        public string PONo { get; set; }
        public string ReqBy { get; set; }
        public string SuppCode { get; set; }
        public string SuppName { get; set; }
        public string SuppAddr { get; set; }
        public string PartyCode { get; set; }
        public string PartyName { get; set; }
        public decimal TotalReqQty { get; set; }
        public decimal TotalDispQty { get; set; }
        public decimal TotalRemQty { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal TotalTaxAmt { get; set; }
        public decimal RndOff { get; set; }
        public decimal NetPayable { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public string ActiveStatus { get; set; }
        public string Version { get; set; }
        public decimal UserId { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string UID { get; set; }
    }
}
