//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrnPurchaseReturnMain
    {
        public decimal RId { get; set; }
        public string ReturnNo { get; set; }
        public decimal RNo { get; set; }
        public string ReturnBy { get; set; }
        public string ReturnByName { get; set; }
        public string ReturnTo { get; set; }
        public string ReturnToName { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public string RefNo { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal TaxAmount { get; set; }
        public decimal RndOff { get; set; }
        public decimal NetPayable { get; set; }
        public string RType { get; set; }
        public string Reason { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string ActiveStatus { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public decimal UserID { get; set; }
        public string Version { get; set; }
        public decimal TotalBV { get; set; }
        public decimal TotalRP { get; set; }
        public string UID { get; set; }
        public string OrderNo { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public int FSessId { get; set; }
        public string EntryBy { get; set; }
        public decimal CGSTAmt { get; set; }
        public decimal SGSTAmt { get; set; }
    }
}
