//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrnPayModeDetail
    {
        public decimal AId { get; set; }
        public decimal FSessId { get; set; }
        public decimal SBillNo { get; set; }
        public string BillNo { get; set; }
        public string SoldBy { get; set; }
        public System.DateTime BillDate { get; set; }
        public string PayPrefix { get; set; }
        public string PayMode { get; set; }
        public string ChqDDNo { get; set; }
        public Nullable<System.DateTime> ChqDDDate { get; set; }
        public string CardNo { get; set; }
        public decimal BankCode { get; set; }
        public string BankName { get; set; }
        public decimal Amount { get; set; }
        public decimal BillAmt { get; set; }
        public string Narration { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string Version { get; set; }
        public decimal UserId { get; set; }
        public string UserName { get; set; }
        public string BillType { get; set; }
        public decimal DUserId { get; set; }
        public Nullable<System.DateTime> DRecTimeStamp { get; set; }
        public string AcNo { get; set; }
        public string IFSCode { get; set; }
    }
}
