//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrnPaymentHoldDetail
    {
        public decimal AID { get; set; }
        public decimal FormNo { get; set; }
        public decimal SessID { get; set; }
        public string IDNo { get; set; }
        public decimal Amount { get; set; }
        public string Status { get; set; }
        public string PType { get; set; }
        public string Reason { get; set; }
        public string Remarks { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string Version { get; set; }
        public decimal UserID { get; set; }
    }
}
