//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrnReceiptDetail
    {
        public decimal BillId { get; set; }
        public string RptNo { get; set; }
        public decimal SRptNo { get; set; }
        public System.DateTime RDate { get; set; }
        public string SoldBy { get; set; }
        public decimal FormNo { get; set; }
        public string ProductId { get; set; }
        public string ProductName { get; set; }
        public string BatchNo { get; set; }
        public decimal Qty { get; set; }
        public decimal Rate { get; set; }
        public decimal BV { get; set; }
        public decimal BvValue { get; set; }
        public string TaxType { get; set; }
        public decimal Tax { get; set; }
        public decimal TaxAmount { get; set; }
        public decimal NetAmount { get; set; }
        public string Series { get; set; }
        public string Remarks { get; set; }
        public string BillFor { get; set; }
        public string Imported { get; set; }
    }
}
