//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrnReceipt
    {
        public decimal RId { get; set; }
        public string SoldBy { get; set; }
        public decimal RptNo { get; set; }
        public string ReceiptNo { get; set; }
        public System.DateTime RDate { get; set; }
        public decimal FormNo { get; set; }
        public string PartyName { get; set; }
        public decimal RefId { get; set; }
        public string RefName { get; set; }
        public string PayMode { get; set; }
        public decimal PackageId { get; set; }
        public string PackageName { get; set; }
        public decimal PackageAmount { get; set; }
        public decimal Qty { get; set; }
        public decimal RP { get; set; }
        public decimal RPValue { get; set; }
        public decimal OrderIncome { get; set; }
        public decimal TotalOrderIncome { get; set; }
        public decimal ChNo { get; set; }
        public System.DateTime ChDate { get; set; }
        public decimal Amount { get; set; }
        public decimal TaxAmount { get; set; }
        public decimal RndOff { get; set; }
        public decimal NetPayable { get; set; }
        public decimal Balance { get; set; }
        public decimal CVValue { get; set; }
        public decimal BalanceCV { get; set; }
        public string Series { get; set; }
        public string Scratch { get; set; }
        public string Status { get; set; }
        public string ActiveStatus { get; set; }
        public string Remarks { get; set; }
        public string Reference { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string DeliveryPlace { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string RefCity { get; set; }
        public decimal RefMobileNo { get; set; }
        public string RptStatus { get; set; }
        public string IDType { get; set; }
        public string SponsorID { get; set; }
        public string SponsorName { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public string RPLeg { get; set; }
        public string IsMaxDate { get; set; }
        public string ReceiptBy { get; set; }
        public decimal PV { get; set; }
        public decimal PVValue { get; set; }
        public string CancelBy { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public string CancelReason { get; set; }
        public decimal CUserId { get; set; }
    }
}
