//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrnSampleProduct
    {
        public decimal AID { get; set; }
        public string TransNo { get; set; }
        public System.DateTime TransDate { get; set; }
        public string RefNo { get; set; }
        public string BillNO { get; set; }
        public string SoldBy { get; set; }
        public string PartyName { get; set; }
        public string ProdID { get; set; }
        public string ProductName { get; set; }
        public string Barcode { get; set; }
        public string BatchNo { get; set; }
        public decimal Qty { get; set; }
        public string ActiveStatus { get; set; }
        public string Remarks { get; set; }
        public decimal UserID { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
    }
}
