//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrnUpdateBillDetail
    {
        public decimal AID { get; set; }
        public string BillNo { get; set; }
        public System.DateTime OldBillDate { get; set; }
        public System.DateTime NewBillDate { get; set; }
        public string Billtype { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public decimal UserId { get; set; }
    }
}
