//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_AvailProdStockBarcodes
    {
        public Nullable<long> RwNo { get; set; }
        public string ProdID { get; set; }
        public string Barcode { get; set; }
        public string BatchNO { get; set; }
        public Nullable<decimal> Qty { get; set; }
    }
}
