//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_BillWiseSaleSummary
    {
        public decimal FSessId { get; set; }
        public string OrderNo { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public decimal UserSBillNo { get; set; }
        public string UserBillNo { get; set; }
        public decimal SBillNo { get; set; }
        public string BillNo { get; set; }
        public string BillDateStr { get; set; }
        public System.DateTime BillDate { get; set; }
        public Nullable<decimal> GroupId { get; set; }
        public string GroupName { get; set; }
        public string PartyCode { get; set; }
        public string PartyName { get; set; }
        public decimal Formno { get; set; }
        public string FCode { get; set; }
        public string NewFCode { get; set; }
        public string Name { get; set; }
        public string OrderType { get; set; }
        public string DownIDNo { get; set; }
        public string DownMemName { get; set; }
        public decimal BillBVValue { get; set; }
        public decimal BVValue { get; set; }
        public decimal RPValue { get; set; }
        public decimal Amount { get; set; }
        public decimal IGSTAmt { get; set; }
        public decimal SGSTAmt { get; set; }
        public decimal CGSTAmt { get; set; }
        public decimal OfferUID { get; set; }
        public decimal TaxAmount { get; set; }
        public decimal NetAmt { get; set; }
        public string PayMode { get; set; }
        public decimal RefId { get; set; }
        public string RefName { get; set; }
        public string KitName { get; set; }
        public string Series { get; set; }
        public string BType { get; set; }
        public string BillType { get; set; }
        public string IsReceive { get; set; }
        public string FType { get; set; }
        public string Remarks { get; set; }
        public string DispatchStatus { get; set; }
        public string OfferName { get; set; }
        public string Offers { get; set; }
        public string OfferIDs { get; set; }
        public Nullable<decimal> Mobile { get; set; }
    }
}
