//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_IDWiseBillSummary
    {
        public string BillNo { get; set; }
        public System.DateTime BillDate { get; set; }
        public string IDNo { get; set; }
        public decimal FormNo { get; set; }
        public string MemName { get; set; }
        public decimal BillAmount { get; set; }
        public string PayMode { get; set; }
        public string BankName { get; set; }
        public decimal ChDDNo { get; set; }
        public Nullable<System.DateTime> ChDate { get; set; }
        public decimal ChAmt { get; set; }
        public string BillPrefix { get; set; }
        public string BillType { get; set; }
    }
}
