//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_MonthWiseSaleSummary
    {
        public string PartyCode { get; set; }
        public string PartyName { get; set; }
        public Nullable<int> BillYear { get; set; }
        public decimal JanQty { get; set; }
        public decimal JanSale { get; set; }
        public decimal FebQty { get; set; }
        public decimal FebSale { get; set; }
        public decimal MarQty { get; set; }
        public decimal MarSale { get; set; }
        public decimal AprQty { get; set; }
        public decimal AprSale { get; set; }
        public decimal MayQty { get; set; }
        public decimal MaySale { get; set; }
        public decimal JunQty { get; set; }
        public decimal JunSale { get; set; }
        public decimal JulQty { get; set; }
        public decimal JulSale { get; set; }
        public decimal AugQty { get; set; }
        public decimal AugSale { get; set; }
        public decimal SepQty { get; set; }
        public decimal SepSale { get; set; }
        public decimal OctQty { get; set; }
        public decimal OctSale { get; set; }
        public decimal NovQty { get; set; }
        public decimal NovSale { get; set; }
        public decimal DecQty { get; set; }
        public decimal DecSale { get; set; }
        public decimal TotalQty { get; set; }
        public decimal TotalSale { get; set; }
    }
}
