//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PaymentModeWiseDetail
    {
        public decimal FSessId { get; set; }
        public string SoldBy { get; set; }
        public string SoldByName { get; set; }
        public string BillNo { get; set; }
        public System.DateTime BillDate { get; set; }
        public string OrderNo { get; set; }
        public string FCode { get; set; }
        public string PartyName { get; set; }
        public decimal BillAmt { get; set; }
        public Nullable<decimal> CashAmt { get; set; }
        public Nullable<decimal> ChqAmt { get; set; }
        public Nullable<decimal> DDAmt { get; set; }
        public Nullable<decimal> CreditCardAmt { get; set; }
        public Nullable<decimal> BankDeposit { get; set; }
        public Nullable<decimal> NEFTRTGS { get; set; }
        public Nullable<decimal> DebitCardAmt { get; set; }
        public Nullable<decimal> NetBanking { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<decimal> WalletAmt { get; set; }
        public Nullable<decimal> VoucherAmt { get; set; }
        public string PayPrefix { get; set; }
        public string Pay_Prefix { get; set; }
    }
}
