//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ProductStockPosition
    {
        public string PartyCode { get; set; }
        public string PartyName { get; set; }
        public Nullable<System.DateTime> StockDate { get; set; }
        public Nullable<decimal> CatId { get; set; }
        public string ProdId { get; set; }
        public string ProductName { get; set; }
        public string BatchCode { get; set; }
        public Nullable<decimal> BV { get; set; }
        public Nullable<decimal> CV { get; set; }
        public Nullable<decimal> PV { get; set; }
        public Nullable<decimal> RP { get; set; }
        public Nullable<decimal> PurchaseRate { get; set; }
        public Nullable<decimal> DP { get; set; }
        public Nullable<decimal> MRP { get; set; }
        public string ProdType { get; set; }
        public string StockType { get; set; }
        public decimal OpBal { get; set; }
        public decimal AddJV { get; set; }
        public decimal SuppPur { get; set; }
        public decimal PartyPur { get; set; }
        public decimal ReturnReceive { get; set; }
        public decimal ChallanIN { get; set; }
        public decimal LessJV { get; set; }
        public decimal SuppPurReturn { get; set; }
        public decimal SaleReturn { get; set; }
        public decimal PartySale { get; set; }
        public decimal ChallanOut { get; set; }
        public decimal PickList { get; set; }
        public decimal PIShrtg { get; set; }
        public Nullable<decimal> CFQty { get; set; }
    }
}
