//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SaleReturnDetail
    {
        public int FSessId { get; set; }
        public decimal MSNo { get; set; }
        public decimal DSNo { get; set; }
        public decimal SRNo { get; set; }
        public string SReturnNo { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public string SoldBy { get; set; }
        public string OrderNo { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string RType { get; set; }
        public string PartyType { get; set; }
        public string ReasonVal { get; set; }
        public string Reason { get; set; }
        public decimal FormNo { get; set; }
        public string ReturnBy { get; set; }
        public string ReturnByName { get; set; }
        public string ReturnTo { get; set; }
        public string ReturnToName { get; set; }
        public decimal TotalBV { get; set; }
        public decimal TotalRP { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal TotalTaxAmout { get; set; }
        public decimal RndOff { get; set; }
        public decimal NetPayable { get; set; }
        public string ProdId { get; set; }
        public string BatchNo { get; set; }
        public string ProductName { get; set; }
        public decimal ReturnQty { get; set; }
        public decimal BV { get; set; }
        public decimal BVValue { get; set; }
        public decimal RP { get; set; }
        public decimal RPValue { get; set; }
        public decimal MRP { get; set; }
        public decimal DP { get; set; }
        public decimal Rate { get; set; }
        public string TaxType { get; set; }
        public decimal Amount { get; set; }
        public decimal Tax { get; set; }
        public decimal TaxAmount { get; set; }
        public Nullable<decimal> TotalAmt { get; set; }
        public string IsKit { get; set; }
        public string ProdType { get; set; }
        public string Remarks { get; set; }
    }
}
