//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_specialProdductDP
    {
        public string ProdId { get; set; }
        public string ImagePath { get; set; }
        public string ProductName { get; set; }
        public decimal Price { get; set; }
        public decimal BV { get; set; }
        public decimal MRP { get; set; }
        public decimal Discount { get; set; }
        public int Qty { get; set; }
        public string Liner { get; set; }
        public string IsForPC { get; set; }
        public string IsFlexible { get; set; }
        public string HotSell { get; set; }
    }
}
