//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_StockRecvSummary
    {
        public decimal FSessId { get; set; }
        public decimal SGrNo { get; set; }
        public string UserBillNo { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public string PartyCode { get; set; }
        public string PartyName { get; set; }
        public string OrderNo { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string BillNo { get; set; }
        public string FCode { get; set; }
        public string Name { get; set; }
        public decimal Amount { get; set; }
        public decimal TaxAmount { get; set; }
        public Nullable<decimal> NetAmt { get; set; }
        public string PayMode { get; set; }
        public string Series { get; set; }
        public string BType { get; set; }
        public string IsReceive { get; set; }
        public string FType { get; set; }
    }
}
