//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_User
    {
        public string Blank { get; set; }
        public decimal GroupId { get; set; }
        public string GroupName { get; set; }
        public decimal UserId { get; set; }
        public string UserName { get; set; }
        public string Passw { get; set; }
        public string Remarks { get; set; }
        public string ActiveStatus { get; set; }
    }
}
