//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_WebBillDetail
    {
        public string BillNo { get; set; }
        public System.DateTime BillDate { get; set; }
        public string IDNo { get; set; }
        public string MemName { get; set; }
        public decimal InvoiceBV { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal TotalTaxAmount { get; set; }
        public decimal NetPayable { get; set; }
        public string PartyCode { get; set; }
        public string PartyName { get; set; }
        public string ProductId { get; set; }
        public string ProductName { get; set; }
        public decimal BVValue { get; set; }
        public decimal Qty { get; set; }
        public decimal MRP { get; set; }
        public decimal DP { get; set; }
        public decimal Rate { get; set; }
        public decimal NetAmount { get; set; }
        public decimal Tax { get; set; }
        public decimal TaxAmount { get; set; }
        public Nullable<decimal> TotalAmt { get; set; }
    }
}
