//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisionOfferProducts_26Aug
    {
        public decimal AID { get; set; }
        public decimal OfferID { get; set; }
        public string ProdID { get; set; }
        public string ProdName { get; set; }
        public decimal Qty { get; set; }
        public string IsConfirm { get; set; }
        public Nullable<decimal> OfferPV { get; set; }
        public Nullable<decimal> OfferPVPer { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime RectimeStamp { get; set; }
        public string IsBuyProduct { get; set; }
        public string IsBVApplied { get; set; }
        public string OnMRP { get; set; }
        public string scheme { get; set; }
        public decimal discount { get; set; }
        public decimal discountPer { get; set; }
        public decimal ForRupee { get; set; }
        public string InculdeInOffer { get; set; }
    }
}
