//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisionOffers08Sep18
    {
        public int AID { get; set; }
        public System.DateTime OfferFromDt { get; set; }
        public System.DateTime OfferToDt { get; set; }
        public string OfferDatePart { get; set; }
        public decimal OfferOnValue { get; set; }
        public string OfferExceptSubCat { get; set; }
        public string FreeProdIDs { get; set; }
        public decimal FreeProdQty { get; set; }
        public decimal OfferOnBV { get; set; }
        public string ConfFreeProdIDs { get; set; }
        public string ConfFreeProdQtys { get; set; }
    }
}
