//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WalletReq
    {
        public decimal AID { get; set; }
        public decimal ReqNo { get; set; }
        public System.DateTime ReqDate { get; set; }
        public string ReqBy { get; set; }
        public decimal PID { get; set; }
        public string Paymode { get; set; }
        public decimal Amount { get; set; }
        public string ChqNo { get; set; }
        public System.DateTime ChqDate { get; set; }
        public string BankName { get; set; }
        public string BranchName { get; set; }
        public string ScannedFile { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string IsApprove { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public decimal ApproveBy { get; set; }
        public string Remarks { get; set; }
        public string TransNo { get; set; }
        public decimal BankId { get; set; }
        public string ApproveRemark { get; set; }
    }
}
