//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    
    public partial class WalletReport_Result1
    {
        public System.DateTime VoucherDateOnly { get; set; }
        public System.DateTime VoucherDate { get; set; }
        public string Narration { get; set; }
        public string DepositedAmt { get; set; }
        public string UsedAmt { get; set; }
        public Nullable<decimal> Balance { get; set; }
    }
}
